site_name: Gestão de Inventário
theme:
  name: material
nav:
  - Home: index.md
  - Sprints: 
    - "Sprint 0": sprints/sprint-00.md
    - "Sprint 1": sprints/sprint-01.md
    - "Sprint 2": sprints/sprint-02.md
    - "Sprint 3": sprints/sprint-03.md
    - "Sprint 4": sprints/sprint-04.md
    - "Sprint 5": sprints/sprint-05.md